# This file was generated by GoReleaser. DO NOT EDIT.
class Haaukins < Formula
  desc "Haaukins CLI"
  homepage "https://github.com/aau-network-security/haaukins/"
  version "2.2.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aau-network-security/haaukins/releases/download/2.2.4/haaukins_cli_2.2.4_macOS_64-bit.zip"
    sha256 "93f3f6c5723add50618b16b2e9dd4138b266ede6a858072b0a0d3ef59752afaf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aau-network-security/haaukins/releases/download/2.2.4/haaukins_cli_2.2.4_linux_64-bit.zip"
      sha256 "d0e167864c97a2322ef04cd5c0795be133f6e9f2ada393a68f5ac6221f8f86e8"
    end
  end

  def install
    bin.install "hkn"
  end

  test do
    system "#{bin}/hkn --help"
  end
end
