# This file was generated by GoReleaser. DO NOT EDIT.
class Haaukins < Formula
  desc "Haaukins CLI"
  homepage "https://github.com/aau-network-security/haaukins/"
  version "2.2.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aau-network-security/haaukins/releases/download/2.2.3/haaukins_cli_2.2.3_macOS_64-bit.zip"
    sha256 "0e434d3c9e49a96724aee61497734822ad872ed2556f04f57f86c2cc4ae54fbb"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aau-network-security/haaukins/releases/download/2.2.3/haaukins_cli_2.2.3_linux_64-bit.zip"
      sha256 "8464d3e70bb7d3ad072cd72bf453eaff1faafd2ddd52de15e73886499af731f4"
    end
  end

  def install
    bin.install "hkn"
  end

  test do
    system "#{bin}/hkn --help"
  end
end
